In [ ]:
'''
import subprocess
from pathlib import Path
from concurrent.futures import ThreadPoolExecutor
from tqdm import tqdm
import shutil

target = Path('./data/2_frame_files')
subdirs = sorted([d for d in target.iterdir() if d.is_dir()])
print(subdirs[:5])

def rm_rf(path):
    subprocess.run(['rm', '-rf', str(path)])

for subdir in tqdm(subdirs, desc="삭제 중"):
    # 하위폴더 내부의 폴더들을 병렬로 rm -rf
    inner_dirs = [d for d in subdir.iterdir() if d.is_dir()]
    if inner_dirs:
        with ThreadPoolExecutor(max_workers=8196) as pool:
            list(pool.map(rm_rf, inner_dirs))
    shutil.rmtree(subdir)

# 남은 최상위 파일 및 폴더 정리
subprocess.run(['rm', '-rf', str(target)])
'''

In [1]:
import pandas as pd

df = pd.read_parquet("./crawl/3_ocr_results/14F 일사에프.parquet")
print(df.shape)
print(df.columns.tolist())
df.head()

(52470, 5)
['file_name', 'frame_num', 'ocr_bbox', 'ocr_text', 'ocr_score']

,file_name,frame_num,ocr_bbox,ocr_text,ocr_score
0,#Shorts 강남 찐 한국인 테스트__crcgq8s1kLQ,1,"[[87.5, 45.5, 89.0, 49.0, 0.0], [649.500061035...","[세A, 1F, 연구소]","[0.926378607749939, 0.40944212675094604, 0.963..."
1,#Shorts 강남 찐 한국인 테스트__crcgq8s1kLQ,2,"[[87.0, 45.5, 90.0, 49.0, 0.0], [649.5, 69.0, ...","[세A, IF, 연구소]","[0.7756869792938232, 0.7911874055862427, 0.965..."
2,#Shorts 강남 찐 한국인 테스트__crcgq8s1kLQ,3,"[[88.0, 46.5, 88.0, 45.0, 0.0], [649.5, 68.999...","[세A, 14F, 연구소, 귀화시험에, 나오는문제는?]","[0.6578993797302246, 0.5935339331626892, 0.999..."
3,#Shorts 강남 찐 한국인 테스트__crcgq8s1kLQ,4,"[[87.5, 44.5, 87.0, 45.0, 0.0], [649.780090332...","[세A, 14F, 연구소, 귀화시험에, 나오는문제는?]","[0.6559808254241943, 0.6293399930000305, 0.995..."
4,#Shorts 강남 찐 한국인 테스트__crcgq8s1kLQ,5,"[[87.5, 46.0, 85.0, 42.0, 0.0], [649.5, 69.5, ...","[세A, 145, 연구소, 귀화시험에, 나오는문제는?]","[0.6533631086349487, 0.5697694420814514, 0.997..."

In [3]:
import pandas as pd

df = pd.read_parquet("./data/_3_ocr_results/14F 일사에프/#Shorts 강남 찐 한국인 테스트__crcgq8s1kLQ.parquet")
print(df.shape)
print(df.columns.tolist())
df.head()

(206, 7)
['frame_num', 'ocr_texts', 'ocr_scores', 'ocr_xywha', 'craft_texts', 'craft_xywha', 'craft_parent_idx']

,frame_num,ocr_texts,ocr_scores,ocr_xywha,craft_texts,craft_xywha,craft_parent_idx
0,1,"[""세A"", ""1F"", ""연구소""]","[0.9264, 0.4094, 0.9633]","[[87.5, 45.5, 89.0, 49.0, 0.0], [649.500061035...","[""세"", ""A"", ""1F"", ""연"", ""연"", ""구"", ""구"", ""소"", ""소""]","[[71.99242401123047, 52.30555725097656, 46.005...","[0, 0, 1, 2, 2, 2, 2, 2, 2]"
1,2,"[""세A"", ""IF"", ""연구소""]","[0.7757, 0.7912, 0.9655]","[[87.0, 45.5, 90.0, 49.0, 0.0], [649.5, 69.0, ...","[""세"", ""A"", ""IF"", ""연"", ""연"", ""구"", ""구"", ""소"", ""소""]","[[70.98876190185547, 52.986106872558594, 44.23...","[0, 0, 1, 2, 2, 2, 2, 2, 2]"
2,3,"[""세A"", ""14F"", ""연구소"", ""귀화시험에"", ""나오는문제는?""]","[0.6579, 0.5935, 0.999, 0.9997, 0.9999]","[[88.0, 46.5, 88.0, 45.0, 0.0], [649.5, 68.999...","[""세"", ""A"", ""A"", ""1"", ""4F"", ""연"", ""구"", ""소"", ""귀"",...","[[71.64751434326172, 47.18181610107422, 40.324...","[0, 0, 0, 1, 1, 2, 2, 2, 3, 3, 3, 3, 3, 4, 4, ..."
3,4,"[""세A"", ""14F"", ""연구소"", ""귀화시험에"", ""나오는문제는?""]","[0.656, 0.6293, 0.9958, 0.9997, 0.9999]","[[87.5, 44.5, 87.0, 45.0, 0.0], [649.780090332...","[""세"", ""A"", ""A"", ""1"", ""4F"", ""연"", ""구"", ""소"", ""귀"",...","[[71.65116119384766, 47.227272033691406, 40.33...","[0, 0, 0, 1, 1, 2, 2, 2, 3, 3, 3, 3, 3, 4, 4, ..."
4,5,"[""세A"", ""145"", ""연구소"", ""귀화시험에"", ""나오는문제는?""]","[0.6534, 0.5698, 0.9979, 0.9996, 0.9999]","[[87.5, 46.0, 85.0, 42.0, 0.0], [649.5, 69.5, ...","[""세"", ""A"", ""A"", ""145"", ""연"", ""구"", ""소"", ""귀"", ""화""...","[[71.30952453613281, 46.853660583496094, 40.34...","[0, 0, 0, 1, 2, 2, 2, 3, 3, 3, 3, 3, 4, 4, 4, ..."

In [6]:
import pandas as pd

df = pd.read_parquet("./data/3_ocr_results/14F 일사에프/#Shorts 강남 찐 한국인 테스트__crcgq8s1kLQ.parquet")
print(df.shape)
print(df.columns.tolist())
df.head()

(206, 7)
['frame_num', 'ocr_texts', 'ocr_scores', 'ocr_xywha', 'craft_texts', 'craft_xywha', 'craft_parent_idx']

,frame_num,ocr_texts,ocr_scores,ocr_xywha,craft_texts,craft_xywha,craft_parent_idx
0,1,"[""세A"", ""1F"", ""연구소""]","[0.9264, 0.4094, 0.9633]","[[87.5, 45.5, 89.0, 49.0, 0.0], [649.500061035...","[""세"", ""A"", ""1"", ""F"", ""연"", ""연"", ""구"", ""구"", ""소"", ...","[[71.99242401123047, 52.30555725097656, 46.005...","[0, 0, 1, 1, 2, 2, 2, 2, 2, 2]"
1,2,"[""세A"", ""IF"", ""연구소""]","[0.7757, 0.7912, 0.9655]","[[87.0, 45.5, 90.0, 49.0, 0.0], [649.5, 69.0, ...","[""세"", ""A"", ""IF"", ""연"", ""연"", ""구"", ""구"", ""소"", ""소""]","[[70.98876190185547, 52.986106872558594, 44.23...","[0, 0, 1, 2, 2, 2, 2, 2, 2]"
2,3,"[""세A"", ""14F"", ""연구소"", ""귀화시험에"", ""나오는문제는?""]","[0.6579, 0.5935, 0.999, 0.9997, 0.9999]","[[88.0, 46.5, 88.0, 45.0, 0.0], [649.5, 68.999...","[""세"", ""A"", ""A"", ""1"", ""4F"", ""연"", ""구"", ""소"", ""귀"",...","[[71.64751434326172, 47.18181610107422, 40.324...","[0, 0, 0, 1, 1, 2, 2, 2, 3, 3, 3, 3, 3, 4, 4, ..."
3,4,"[""세A"", ""14F"", ""연구소"", ""귀화시험에"", ""나오는문제는?""]","[0.656, 0.6293, 0.9958, 0.9997, 0.9999]","[[87.5, 44.5, 87.0, 45.0, 0.0], [649.780090332...","[""세"", ""A"", ""A"", ""1"", ""4F"", ""연"", ""구"", ""소"", ""귀"",...","[[71.65116119384766, 47.227272033691406, 40.33...","[0, 0, 0, 1, 1, 2, 2, 2, 3, 3, 3, 3, 3, 4, 4, ..."
4,5,"[""세A"", ""145"", ""연구소"", ""귀화시험에"", ""나오는문제는?""]","[0.6534, 0.5698, 0.9979, 0.9996, 0.9999]","[[87.5, 46.0, 85.0, 42.0, 0.0], [649.5, 69.5, ...","[""세"", ""A"", ""A"", ""145"", ""연"", ""구"", ""소"", ""귀"", ""화""...","[[71.30952453613281, 46.853660583496094, 40.34...","[0, 0, 0, 1, 2, 2, 2, 3, 3, 3, 3, 3, 4, 4, 4, ..."